import '../styles/globals.css';
import type { AppProps } from 'next/app';

import Head from 'next/head';

function MyApp({Component, pageProps,router}: AppProps) {
  return <>
    <Head>
      <title>Create Next App</title>

      <meta name="description" content="Generated by create next app"/>
      <meta property={'og:url'} content={process.env.NEXT_PUBLIC_DOMAIN + router.asPath}/>
      <meta property={'og:locale'} content={'ru_RU'}/>

      <link rel="icon" href="/purple-book.svg"/>
    </Head>
    <Component {...pageProps} />
  </>;
}

export default MyApp;
